export const PO_STATUS_DRAFT = "DRAFT";
export const PO_STATUS_SUBMITTED = "SUBMITTED";
export const PO_STATUS_PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED";
export const PO_STATUS_RECEIVED = "RECEIVED";
export const PO_STATUS_CLOSED = "CLOSED";
export const PO_STATUS_CANCELLED = "CANCELLED";

export const PO_RECEIVABLE_STATUSES = new Set([
  PO_STATUS_SUBMITTED,
  PO_STATUS_PARTIALLY_RECEIVED,
]);
